# Generated by Django 5.2.3 on 2025-11-14 03:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import reklamaproject.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ijarachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ijarachi_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qurilmaturi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Joy raqami, masalan: 1, 2, 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pozitsiya',
                'verbose_name_plural': 'Pozitsiyalar',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reklama_nomi', models.CharField(default='Reklama nomi', max_length=255)),
                ('Shartnoma_raqami', models.CharField(blank=True, help_text="Shartnoma raqami o'zbekcha", max_length=100, null=True)),
                ('Shartnoma_muddati_boshlanishi', models.DateField()),
                ('Shartnoma_tugashi', models.DateField()),
                ('O_lchov_birligi', models.CharField(choices=[('dona', 'Dona'), ('kv_metr', 'Kv metr'), ('komplekt', 'Komplekt')], default='dona', max_length=50)),
                ('Qurilma_narxi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Egallagan_maydon', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('Shartnoma_summasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Shartnoma_fayl', models.FileField(blank=True, default=None, null=True, upload_to='contracts/', validators=[reklamaproject.validators.validate_file_extension])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ad_photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('Ijarachi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.ijarachi')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='reklamaproject.position')),
                ('Qurilma_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.turi')),
            ],
        ),
        migrations.CreateModel(
            name='ShartnomaSummasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shartnomasummasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='reklamaproject.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('schema_image', models.FileField(blank=True, help_text='Bekat sxemasi (rasm yoki PDF)', null=True, upload_to='station_schemas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='reklamaproject.metroline')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='reklamaproject.station'),
        ),
        migrations.CreateModel(
            name='AdvertisementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reklama_nomi', models.CharField(max_length=255)),
                ('Shartnoma_raqami', models.CharField(blank=True, max_length=100, null=True)),
                ('Shartnoma_muddati_boshlanishi', models.DateField()),
                ('Shartnoma_tugashi', models.DateField()),
                ('O_lchov_birligi', models.CharField(max_length=50)),
                ('Qurilma_narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Egallagan_maydon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shartnoma_summasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Shartnoma_fayl', models.FileField(blank=True, null=True, upload_to='contracts_archive/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ad_photos_archive/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='reklamaproject.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Ijarachi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.ijarachi')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.metroline')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.position')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.station')),
                ('Qurilma_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.turi')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('station', 'number')},
        ),
    ]
