# Generated by Django 5.2.3 on 2026-06-04 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0019_alter_tarkibposition_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmmaviyTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_summa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('har_biri_uchun_summa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ijarachi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ommaviy_tolovlar', to='reklamaproject.ijarachi')),
            ],
        ),
        migrations.AddField(
            model_name='shartnomasummasi',
            name='ommaviy_tolov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qismlari', to='reklamaproject.ommaviytolov'),
        ),
    ]
