# Generated by Django 5.2.3 on 2026-06-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0021_ijaragajoy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ijaragajoy',
            name='kv_metr',
        ),
        migrations.AddField(
            model_name='ijaragajoy',
            name='maydoni',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Joy maydoni yoki miqdori', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ijaragajoy',
            name='o_lchov_birligi',
            field=models.CharField(choices=[('dona', 'Dona'), ('kv_metr', 'Kv metr'), ('komplekt', 'Komplekt')], default='kv_metr', help_text="O'lchov birligi", max_length=50),
        ),
    ]
