# Generated by Django 5.2.3 on 2026-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0022_remove_ijaragajoy_kv_metr_ijaragajoy_maydoni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='maydoni',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Joy maydoni yoki miqdori', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='o_lchov_birligi',
            field=models.CharField(blank=True, choices=[('dona', 'Dona'), ('kv_metr', 'Kv metr'), ('komplekt', 'Komplekt')], default='kv_metr', help_text="O'lchov birligi", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='photo',
            field=models.ImageField(blank=True, help_text='Joy rasmi', null=True, upload_to='position_photos/'),
        ),
        migrations.DeleteModel(
            name='IjaragaJoy',
        ),
    ]
