# Generated by Django 5.2.3 on 2026-06-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0023_position_maydoni_position_o_lchov_birligi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='turi',
            field=models.ForeignKey(blank=True, help_text='Reklama qurilma turi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='reklamaproject.turi'),
        ),
    ]
