# Generated by Django 5.2.3 on 2026-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0024_position_turi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijarachi',
            name='Shartnoma_muddati_boshlanishi',
            field=models.DateField(blank=True, help_text='Shartnoma boshlanish sanasi', null=True),
        ),
        migrations.AddField(
            model_name='ijarachi',
            name='Shartnoma_tugashi',
            field=models.DateField(blank=True, help_text='Shartnoma tugash sanasi', null=True),
        ),
    ]
