# Generated by Django 5.2.3 on 2026-06-26 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0025_ijarachi_shartnoma_muddati_boshlanishi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IjaragaJoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joylashuvi', models.CharField(help_text='Qayer ekani (bekat nomi yoki boshqa joy)', max_length=255)),
                ('maydoni', models.DecimalField(blank=True, decimal_places=2, help_text='Joy maydoni yoki miqdori', max_digits=10, null=True)),
                ('o_lchov_birligi', models.CharField(choices=[('dona', 'Dona'), ('kv_metr', 'Kv metr'), ('komplekt', 'Komplekt')], default='kv_metr', help_text="O'lchov birligi", max_length=50)),
                ('photo', models.ImageField(blank=True, help_text='Joy rasmi', null=True, upload_to='ijaraga_joylar/')),
                ('status', models.CharField(choices=[("bo'sh", "Bo'sh"), ('band', 'Band')], default="bo'sh", help_text="Statusi (bo'sh yoki band)", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turi', models.ForeignKey(blank=True, help_text='Joy turi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ijaraga_joylar', to='reklamaproject.turi')),
            ],
            options={
                'verbose_name': 'Ijaraga beriladigan joy',
                'verbose_name_plural': 'Ijaraga beriladigan joylar',
            },
        ),
    ]
