# Generated by Django 5.2.3 on 2026-06-26 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0026_recreate_ijaragajoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijaragajoy',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Bekat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ijaraga_joylar', to='reklamaproject.station'),
        ),
        migrations.AlterField(
            model_name='ijaragajoy',
            name='joylashuvi',
            field=models.CharField(help_text="Qo'shimcha joy tavsifi (masalan: 1-qavat, kirish oldi)", max_length=255),
        ),
    ]
