# Generated by Django 5.2.3 on 2026-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0027_ijaragajoy_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ijaragajoy',
            name='joylashuvi',
            field=models.CharField(blank=True, default='', help_text="Qo'shimcha joy tavsifi (masalan: 1-qavat, kirish oldi)", max_length=255),
        ),
    ]
