# Generated by Django 5.2.3 on 2026-06-26 08:42

import reklamaproject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0028_ijaragajoy_joylashuvi_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ad_videos/', validators=[reklamaproject.validators.validate_video_extension]),
        ),
        migrations.AddField(
            model_name='advertisementarchive',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ad_videos_archive/', validators=[reklamaproject.validators.validate_video_extension]),
        ),
        migrations.AddField(
            model_name='tarkibadvertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ad_videos/', validators=[reklamaproject.validators.validate_video_extension]),
        ),
        migrations.AddField(
            model_name='tarkibadvertisementarchive',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ad_videos_archive/', validators=[reklamaproject.validators.validate_video_extension]),
        ),
    ]
