# Generated by Django 5.2.3 on 2026-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0029_advertisement_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='maydoni',
        ),
        migrations.RemoveField(
            model_name='position',
            name='o_lchov_birligi',
        ),
        migrations.RemoveField(
            model_name='position',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='position',
            name='turi',
        ),
    ]
